name: Deploy frontend
on:
    push:
        branches:
            - dev
        paths:
            - '.github/workflows/**'
            - '.deploy/**'
            - 'src/**'
            - 'public/**'
            - 'messages/**'
    pull_request:
            branches:
                - dev


jobs:
    build-and-push-docker-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/dev'
        steps:
            - uses: actions/checkout@v2
            - run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -f .docker/Dockerfile -t 3444866/welpfront .
            - run: docker push 3444866/welpfront

    deploy-app:
        name: Deploy
        runs-on: ubuntu-latest
        needs: build-and-push-docker-image
        if: github.ref == 'refs/heads/dev'
        steps:
            - name : ssh
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_KEY }}
                port: ${{ secrets.SERVER_PORT }}
                script: |
                  cd /srv/welp-frontend
                  docker compose down
                  docker compose pull
                  docker compose up prod -d